import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalHeader } from "@/components/layout/GlobalHeader";
import { UserProvider } from "@/context/UserContext";
import { BranchProvider } from "@/context/BranchContext";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "sonner";
import { GoogleMapsProvider } from "@/providers/GoogleMapsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <BranchProvider>
            <CartProvider>
              <GoogleMapsProvider>
                <GlobalHeader />
                {children}
              </GoogleMapsProvider>
              <Toaster position="top-left" richColors toastOptions={{ style: { marginTop: '60px' } }} />
            </CartProvider>
          </BranchProvider>
        </UserProvider>
      </body>
    </html>
  );
}
